# Generated by Django 2.1.7 on 2019-03-10 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='media/')),
                ('description', models.CharField(max_length=500)),
                ('related', models.CharField(choices=[('General', 'General'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Design', 'Design'), ('Ideas', 'Ideas'), ('Politics', 'Politics'), ('Self', 'Self'), ('Health', 'Health'), ('Science', 'Science'), ('Business', 'Business')], default='General', max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
